-- MySQL Script generated by MySQL Workbench
-- Wed Jun 15 16:15:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital` DEFAULT CHARACTER SET utf8mb4 ;
USE `hospital` ;

-- -----------------------------------------------------
-- Table `hospital`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`doctor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `apellido_materno` VARCHAR(255) NULL DEFAULT NULL,
  `apellido_paterno` VARCHAR(255) NULL DEFAULT NULL,
  `especialidas` VARCHAR(255) NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hospital`.`consultorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`consultorio` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `piso` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hospital`.`cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`cita` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `consultorio_id` INT(11) NULL DEFAULT NULL,
  `doctor_id` INT(11) NULL DEFAULT NULL,
  `hora_consulta` DATETIME(6) NULL DEFAULT NULL,
  `nombre_paciente` VARCHAR(255) NULL DEFAULT NULL,
  `doctor_id1` INT(11) NOT NULL,
  `consultorio_id1` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cita_doctor_idx` (`doctor_id1` ASC) VISIBLE,
  INDEX `fk_cita_consultorio1_idx` (`consultorio_id1` ASC) VISIBLE,
  CONSTRAINT `fk_cita_doctor`
    FOREIGN KEY (`doctor_id1`)
    REFERENCES `hospital`.`doctor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cita_consultorio1`
    FOREIGN KEY (`consultorio_id1`)
    REFERENCES `hospital`.`consultorio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
